import type { Metadata } from "next";

// styles
import "./globals.css";
import styles from "@/styles";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={` relative w-screen h-screen ${geistSans.variable} ${geistMono.variable} antialiased ${styles.flexCenter}`}
        >
          <div className="mainContent">{children}</div>
        </body>
      </ThemeProvider>
    </html>
  );
}
